server:
  port: 80
  context-path: /shop
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/shop?characterEncoding=utf8
logging:
  path: D:/project/shop/logs